### ISSUE TITLE
Convert Tiff to netCDF

### ISSUE THREAD

**Issue by tsga** [CI-WATER/portal#4]
Tool to generate netCDF file from a Tiff file. The contents of the netCDF will be determined by the variable in the Tiff file. The array information such as the coordinates, projection (if any) will be copied from the Tiff file.
Example usage: Convert slope Tiff file to a 2D netCDF with slope as the variable
Input: Tiff file
Input: Variable name
Output: A 2D netCDF with the variable values from the Tiff file

**Comment by tsapin** [comment]
Hi,
Sorry I am new in this community. where I can find this tool? I really need to convert my tiffs into CDF. Thanks!
Ilya

**Comment by tsga** [comment]
Hi, You can use gdal as follows:

gdal_translate -of netCDF -co "FORMAT=NC4"     "input_raster.tif"  "output_netcdf.nc"

**Comment by tsapin** [comment]
Thank you so much!
also - do you know anything about size limitations? I am trying to convert 2 gb file and it ran for last several hours with no outcome...
thanks!

**Comment by tsga** [comment]
no I don't know what the size limitation is (or if there is one) but 2GB is not too big. The problem might be something else.
You can find more info here: https://gdal.org/programs/gdal_translate.html#gdal-translate

If you want you can share sample tiff file and I can try it.

**Comment by ajay-kumar-natwariya** [comment]
Hey tsga can you please explane me how to convert it. I have difficulty in this?

**Comment by tsga** [comment]
Ajay,
The tool described here is a Python wrapper for the GDAL command line call:
gdal_translate -of netCDF  input_raster.tif output_netcdf.nc

You don't need Python to call the above from command line. You need to install GDAL first (https://gdal.org/programs/gdal_translate.html#gdal-translate).

**Comment by ajay-kumar-natwariya** [comment]
can you do this for me and send me python script for my file.

**Comment by AjayKumarNatwariya** [comment]
Please
https://drive.google.com/file/d/1CJLXXsVbrUMCyK_lLcuFYSRoPmjIRc1w/view?usp=sharing

**Comment by Zhyu-1** [comment]
Hi,

I want to convert TIFF to NC with time series, can this tool help me? And if so, how to achieve this goal?

Thanks

**Comment by tsga** [comment]
Zhyu-1, 

You have to use a script that loops through the time steps to do that. And you can use a combination of GDAL and NCO (netCDF Operators) to achieve that.

1. If you have separate Tiff files for each time step, take a look at the function create_netCDF_from_multple_Tiff() in the attached sample script.
Basically, first you convert Tiff to netCDF. Then you combine the netCDFs by creating a record dimension (Time).

2. If your single Tiff file has data for all time steps (i.e., multiple Bands), you can read each band data as array, then save it as netCDF, then concatenate them. Example in function Raster_band_to_netCDF().

3. Alternatively you can use Python netCDF4 package together with GDAL. (https://pypi.org/project/netCDF4/) 

For more you can take a look around the functions here:
https://github.com/CI-WATER/Hydro-DS/tree/master_plus_uebrun_plus_nldas/usu_data_service/servicefunctions

And you can read more about it here:
https://www.researchgate.net/publication/338484278_HydroDS_Data_Services_in_Support_of_Physically_Based_Distributed_Hydrological_Models

Sample script:
[sampleFuncs.zip](https://github.com/CI-WATER/portal/files/5435571/sampleFuncs.zip)
